# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel


class CatalogOverview(BaseModel):
    categories: Optional["CatalogOverviewCategories"]
    collections: Optional["CatalogOverviewCollections"]


class CatalogOverviewCategories(BaseModel):
    edges: List["CatalogOverviewCategoriesEdges"]


class CatalogOverviewCategoriesEdges(BaseModel):
    node: "CatalogOverviewCategoriesEdgesNode"


class CatalogOverviewCategoriesEdgesNode(BaseModel):
    id: str
    slug: str
    name: str
    products: Optional["CatalogOverviewCategoriesEdgesNodeProducts"]


class CatalogOverviewCategoriesEdgesNodeProducts(BaseModel):
    totalCount: Optional[int]
    edges: List["CatalogOverviewCategoriesEdgesNodeProductsEdges"]


class CatalogOverviewCategoriesEdgesNodeProductsEdges(BaseModel):
    node: "CatalogOverviewCategoriesEdgesNodeProductsEdgesNode"


class CatalogOverviewCategoriesEdgesNodeProductsEdgesNode(BaseModel):
    id: str
    name: str
    slug: str


class CatalogOverviewCollections(BaseModel):
    edges: List["CatalogOverviewCollectionsEdges"]


class CatalogOverviewCollectionsEdges(BaseModel):
    node: "CatalogOverviewCollectionsEdgesNode"


class CatalogOverviewCollectionsEdgesNode(BaseModel):
    id: str
    slug: str
    name: str
    products: Optional["CatalogOverviewCollectionsEdgesNodeProducts"]


class CatalogOverviewCollectionsEdgesNodeProducts(BaseModel):
    totalCount: Optional[int]


CatalogOverview.model_rebuild()
CatalogOverviewCategories.model_rebuild()
CatalogOverviewCategoriesEdges.model_rebuild()
CatalogOverviewCategoriesEdgesNode.model_rebuild()
CatalogOverviewCategoriesEdgesNodeProducts.model_rebuild()
CatalogOverviewCategoriesEdgesNodeProductsEdges.model_rebuild()
CatalogOverviewCollections.model_rebuild()
CatalogOverviewCollectionsEdges.model_rebuild()
CatalogOverviewCollectionsEdgesNode.model_rebuild()
