# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import CheckoutErrorCode, OrderStatus


class CheckoutComplete(BaseModel):
    checkoutComplete: Optional["CheckoutCompleteCheckoutComplete"]


class CheckoutCompleteCheckoutComplete(BaseModel):
    order: Optional["CheckoutCompleteCheckoutCompleteOrder"]
    errors: List["CheckoutCompleteCheckoutCompleteErrors"]


class CheckoutCompleteCheckoutCompleteOrder(BaseModel):
    id: str
    number: str
    status: OrderStatus


class CheckoutCompleteCheckoutCompleteErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


CheckoutComplete.model_rebuild()
CheckoutCompleteCheckoutComplete.model_rebuild()
