# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import CheckoutErrorCode


class CheckoutShippingAddressUpdate(BaseModel):
    checkoutShippingAddressUpdate: Optional[
        "CheckoutShippingAddressUpdateCheckoutShippingAddressUpdate"
    ]


class CheckoutShippingAddressUpdateCheckoutShippingAddressUpdate(BaseModel):
    checkout: Optional[
        "CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckout"
    ]
    errors: List["CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateErrors"]


class CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckout(BaseModel):
    id: str
    shippingAddress: Optional[
        "CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckoutShippingAddress"
    ]
    availableShippingMethods: List[
        "CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckoutAvailableShippingMethods"
    ]


class CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckoutShippingAddress(
    BaseModel
):
    firstName: str
    lastName: str
    streetAddress1: str
    streetAddress2: str
    city: str
    cityArea: str
    postalCode: str
    country: "CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckoutShippingAddressCountry"
    countryArea: str
    phone: Optional[str]


class CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckoutShippingAddressCountry(
    BaseModel
):
    code: str


class CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckoutAvailableShippingMethods(
    BaseModel
):
    id: str
    name: str
    price: "CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckoutAvailableShippingMethodsPrice"


class CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckoutAvailableShippingMethodsPrice(
    BaseModel
):
    amount: float
    currency: str


class CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


CheckoutShippingAddressUpdate.model_rebuild()
CheckoutShippingAddressUpdateCheckoutShippingAddressUpdate.model_rebuild()
CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckout.model_rebuild()
CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckoutShippingAddress.model_rebuild()
CheckoutShippingAddressUpdateCheckoutShippingAddressUpdateCheckoutAvailableShippingMethods.model_rebuild()
