# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import PaymentErrorCode


class CheckoutPaymentCreate(BaseModel):
    checkoutPaymentCreate: Optional["CheckoutPaymentCreateCheckoutPaymentCreate"]


class CheckoutPaymentCreateCheckoutPaymentCreate(BaseModel):
    payment: Optional["CheckoutPaymentCreateCheckoutPaymentCreatePayment"]
    errors: List["CheckoutPaymentCreateCheckoutPaymentCreateErrors"]


class CheckoutPaymentCreateCheckoutPaymentCreatePayment(BaseModel):
    id: str
    gateway: str
    isActive: bool


class CheckoutPaymentCreateCheckoutPaymentCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: PaymentErrorCode


CheckoutPaymentCreate.model_rebuild()
CheckoutPaymentCreateCheckoutPaymentCreate.model_rebuild()
