# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import CheckoutErrorCode


class CheckoutCreate(BaseModel):
    checkoutCreate: Optional["CheckoutCreateCheckoutCreate"]


class CheckoutCreateCheckoutCreate(BaseModel):
    checkout: Optional["CheckoutCreateCheckoutCreateCheckout"]
    errors: List["CheckoutCreateCheckoutCreateErrors"]


class CheckoutCreateCheckoutCreateCheckout(BaseModel):
    id: str
    token: Any
    totalPrice: "CheckoutCreateCheckoutCreateCheckoutTotalPrice"
    lines: List["CheckoutCreateCheckoutCreateCheckoutLines"]


class CheckoutCreateCheckoutCreateCheckoutTotalPrice(BaseModel):
    gross: "CheckoutCreateCheckoutCreateCheckoutTotalPriceGross"


class CheckoutCreateCheckoutCreateCheckoutTotalPriceGross(BaseModel):
    amount: float
    currency: str


class CheckoutCreateCheckoutCreateCheckoutLines(BaseModel):
    id: str
    quantity: int
    variant: "CheckoutCreateCheckoutCreateCheckoutLinesVariant"


class CheckoutCreateCheckoutCreateCheckoutLinesVariant(BaseModel):
    name: str
    product: "CheckoutCreateCheckoutCreateCheckoutLinesVariantProduct"


class CheckoutCreateCheckoutCreateCheckoutLinesVariantProduct(BaseModel):
    name: str


class CheckoutCreateCheckoutCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


CheckoutCreate.model_rebuild()
CheckoutCreateCheckoutCreate.model_rebuild()
CheckoutCreateCheckoutCreateCheckout.model_rebuild()
CheckoutCreateCheckoutCreateCheckoutTotalPrice.model_rebuild()
CheckoutCreateCheckoutCreateCheckoutLines.model_rebuild()
CheckoutCreateCheckoutCreateCheckoutLinesVariant.model_rebuild()
