# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import CheckoutErrorCode


class CheckoutLinesUpdate(BaseModel):
    checkoutLinesUpdate: Optional["CheckoutLinesUpdateCheckoutLinesUpdate"]


class CheckoutLinesUpdateCheckoutLinesUpdate(BaseModel):
    checkout: Optional["CheckoutLinesUpdateCheckoutLinesUpdateCheckout"]
    errors: List["CheckoutLinesUpdateCheckoutLinesUpdateErrors"]


class CheckoutLinesUpdateCheckoutLinesUpdateCheckout(BaseModel):
    id: str
    lines: List["CheckoutLinesUpdateCheckoutLinesUpdateCheckoutLines"]
    totalPrice: "CheckoutLinesUpdateCheckoutLinesUpdateCheckoutTotalPrice"


class CheckoutLinesUpdateCheckoutLinesUpdateCheckoutLines(BaseModel):
    id: str
    quantity: int
    variant: "CheckoutLinesUpdateCheckoutLinesUpdateCheckoutLinesVariant"


class CheckoutLinesUpdateCheckoutLinesUpdateCheckoutLinesVariant(BaseModel):
    name: str


class CheckoutLinesUpdateCheckoutLinesUpdateCheckoutTotalPrice(BaseModel):
    gross: "CheckoutLinesUpdateCheckoutLinesUpdateCheckoutTotalPriceGross"


class CheckoutLinesUpdateCheckoutLinesUpdateCheckoutTotalPriceGross(BaseModel):
    amount: float
    currency: str


class CheckoutLinesUpdateCheckoutLinesUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


CheckoutLinesUpdate.model_rebuild()
CheckoutLinesUpdateCheckoutLinesUpdate.model_rebuild()
CheckoutLinesUpdateCheckoutLinesUpdateCheckout.model_rebuild()
CheckoutLinesUpdateCheckoutLinesUpdateCheckoutLines.model_rebuild()
CheckoutLinesUpdateCheckoutLinesUpdateCheckoutTotalPrice.model_rebuild()
