# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import CheckoutErrorCode


class CheckoutLinesDelete(BaseModel):
    checkoutLinesDelete: Optional["CheckoutLinesDeleteCheckoutLinesDelete"]


class CheckoutLinesDeleteCheckoutLinesDelete(BaseModel):
    checkout: Optional["CheckoutLinesDeleteCheckoutLinesDeleteCheckout"]
    errors: List["CheckoutLinesDeleteCheckoutLinesDeleteErrors"]


class CheckoutLinesDeleteCheckoutLinesDeleteCheckout(BaseModel):
    id: str
    lines: List["CheckoutLinesDeleteCheckoutLinesDeleteCheckoutLines"]
    totalPrice: "CheckoutLinesDeleteCheckoutLinesDeleteCheckoutTotalPrice"


class CheckoutLinesDeleteCheckoutLinesDeleteCheckoutLines(BaseModel):
    id: str
    quantity: int


class CheckoutLinesDeleteCheckoutLinesDeleteCheckoutTotalPrice(BaseModel):
    gross: "CheckoutLinesDeleteCheckoutLinesDeleteCheckoutTotalPriceGross"


class CheckoutLinesDeleteCheckoutLinesDeleteCheckoutTotalPriceGross(BaseModel):
    amount: float
    currency: str


class CheckoutLinesDeleteCheckoutLinesDeleteErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


CheckoutLinesDelete.model_rebuild()
CheckoutLinesDeleteCheckoutLinesDelete.model_rebuild()
CheckoutLinesDeleteCheckoutLinesDeleteCheckout.model_rebuild()
CheckoutLinesDeleteCheckoutLinesDeleteCheckoutTotalPrice.model_rebuild()
