# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import CheckoutErrorCode


class CheckoutLinesAdd(BaseModel):
    checkoutLinesAdd: Optional["CheckoutLinesAddCheckoutLinesAdd"]


class CheckoutLinesAddCheckoutLinesAdd(BaseModel):
    checkout: Optional["CheckoutLinesAddCheckoutLinesAddCheckout"]
    errors: List["CheckoutLinesAddCheckoutLinesAddErrors"]


class CheckoutLinesAddCheckoutLinesAddCheckout(BaseModel):
    id: str
    lines: List["CheckoutLinesAddCheckoutLinesAddCheckoutLines"]
    totalPrice: "CheckoutLinesAddCheckoutLinesAddCheckoutTotalPrice"


class CheckoutLinesAddCheckoutLinesAddCheckoutLines(BaseModel):
    id: str
    quantity: int
    variant: "CheckoutLinesAddCheckoutLinesAddCheckoutLinesVariant"


class CheckoutLinesAddCheckoutLinesAddCheckoutLinesVariant(BaseModel):
    name: str


class CheckoutLinesAddCheckoutLinesAddCheckoutTotalPrice(BaseModel):
    gross: "CheckoutLinesAddCheckoutLinesAddCheckoutTotalPriceGross"


class CheckoutLinesAddCheckoutLinesAddCheckoutTotalPriceGross(BaseModel):
    amount: float
    currency: str


class CheckoutLinesAddCheckoutLinesAddErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


CheckoutLinesAdd.model_rebuild()
CheckoutLinesAddCheckoutLinesAdd.model_rebuild()
CheckoutLinesAddCheckoutLinesAddCheckout.model_rebuild()
CheckoutLinesAddCheckoutLinesAddCheckoutLines.model_rebuild()
CheckoutLinesAddCheckoutLinesAddCheckoutTotalPrice.model_rebuild()
