# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import CheckoutErrorCode


class CheckoutEmailUpdate(BaseModel):
    checkoutEmailUpdate: Optional["CheckoutEmailUpdateCheckoutEmailUpdate"]


class CheckoutEmailUpdateCheckoutEmailUpdate(BaseModel):
    checkout: Optional["CheckoutEmailUpdateCheckoutEmailUpdateCheckout"]
    errors: List["CheckoutEmailUpdateCheckoutEmailUpdateErrors"]


class CheckoutEmailUpdateCheckoutEmailUpdateCheckout(BaseModel):
    id: str
    email: Optional[str]


class CheckoutEmailUpdateCheckoutEmailUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


CheckoutEmailUpdate.model_rebuild()
CheckoutEmailUpdateCheckoutEmailUpdate.model_rebuild()
