# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Annotated, Any, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class CheckoutDetails(BaseModel):
    checkout: Optional["CheckoutDetailsCheckout"]


class CheckoutDetailsCheckout(BaseModel):
    id: str
    token: Any
    email: Optional[str]
    totalPrice: "CheckoutDetailsCheckoutTotalPrice"
    lines: List["CheckoutDetailsCheckoutLines"]
    shippingAddress: Optional["CheckoutDetailsCheckoutShippingAddress"]
    billingAddress: Optional["CheckoutDetailsCheckoutBillingAddress"]
    deliveryMethod: Optional[
        Annotated[
            Union[
                "CheckoutDetailsCheckoutDeliveryMethodWarehouse",
                "CheckoutDetailsCheckoutDeliveryMethodShippingMethod",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    shippingMethods: List["CheckoutDetailsCheckoutShippingMethods"]
    availableShippingMethods: List["CheckoutDetailsCheckoutAvailableShippingMethods"]
    availablePaymentGateways: List["CheckoutDetailsCheckoutAvailablePaymentGateways"]


class CheckoutDetailsCheckoutTotalPrice(BaseModel):
    gross: "CheckoutDetailsCheckoutTotalPriceGross"


class CheckoutDetailsCheckoutTotalPriceGross(BaseModel):
    amount: float
    currency: str


class CheckoutDetailsCheckoutLines(BaseModel):
    id: str
    quantity: int
    variant: "CheckoutDetailsCheckoutLinesVariant"


class CheckoutDetailsCheckoutLinesVariant(BaseModel):
    name: str
    product: "CheckoutDetailsCheckoutLinesVariantProduct"


class CheckoutDetailsCheckoutLinesVariantProduct(BaseModel):
    name: str


class CheckoutDetailsCheckoutShippingAddress(BaseModel):
    firstName: str
    lastName: str
    streetAddress1: str
    streetAddress2: str
    city: str
    cityArea: str
    postalCode: str
    country: "CheckoutDetailsCheckoutShippingAddressCountry"
    countryArea: str
    phone: Optional[str]


class CheckoutDetailsCheckoutShippingAddressCountry(BaseModel):
    code: str


class CheckoutDetailsCheckoutBillingAddress(BaseModel):
    firstName: str
    lastName: str
    streetAddress1: str
    streetAddress2: str
    city: str
    cityArea: str
    postalCode: str
    country: "CheckoutDetailsCheckoutBillingAddressCountry"
    countryArea: str
    phone: Optional[str]


class CheckoutDetailsCheckoutBillingAddressCountry(BaseModel):
    code: str


class CheckoutDetailsCheckoutDeliveryMethodWarehouse(BaseModel):
    typename__: Literal["Warehouse"] = Field(alias="__typename")
    id: str
    name: str


class CheckoutDetailsCheckoutDeliveryMethodShippingMethod(BaseModel):
    typename__: Literal["ShippingMethod"] = Field(alias="__typename")
    id: str
    name: str


class CheckoutDetailsCheckoutShippingMethods(BaseModel):
    id: str
    name: str
    price: "CheckoutDetailsCheckoutShippingMethodsPrice"


class CheckoutDetailsCheckoutShippingMethodsPrice(BaseModel):
    amount: float
    currency: str


class CheckoutDetailsCheckoutAvailableShippingMethods(BaseModel):
    id: str
    name: str
    price: "CheckoutDetailsCheckoutAvailableShippingMethodsPrice"


class CheckoutDetailsCheckoutAvailableShippingMethodsPrice(BaseModel):
    amount: float
    currency: str


class CheckoutDetailsCheckoutAvailablePaymentGateways(BaseModel):
    id: str
    name: str
    config: List["CheckoutDetailsCheckoutAvailablePaymentGatewaysConfig"]


class CheckoutDetailsCheckoutAvailablePaymentGatewaysConfig(BaseModel):
    field: str
    value: Optional[str]


CheckoutDetails.model_rebuild()
CheckoutDetailsCheckout.model_rebuild()
CheckoutDetailsCheckoutTotalPrice.model_rebuild()
CheckoutDetailsCheckoutLines.model_rebuild()
CheckoutDetailsCheckoutLinesVariant.model_rebuild()
CheckoutDetailsCheckoutShippingAddress.model_rebuild()
CheckoutDetailsCheckoutBillingAddress.model_rebuild()
CheckoutDetailsCheckoutShippingMethods.model_rebuild()
CheckoutDetailsCheckoutAvailableShippingMethods.model_rebuild()
CheckoutDetailsCheckoutAvailablePaymentGateways.model_rebuild()
