# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import CheckoutErrorCode, OrderStatus, PaymentChargeStatusEnum


class CheckoutComplete(BaseModel):
    checkoutComplete: Optional["CheckoutCompleteCheckoutComplete"]


class CheckoutCompleteCheckoutComplete(BaseModel):
    order: Optional["CheckoutCompleteCheckoutCompleteOrder"]
    errors: List["CheckoutCompleteCheckoutCompleteErrors"]


class CheckoutCompleteCheckoutCompleteOrder(BaseModel):
    id: str
    number: str
    status: OrderStatus
    paymentStatus: PaymentChargeStatusEnum
    created: Any
    total: "CheckoutCompleteCheckoutCompleteOrderTotal"


class CheckoutCompleteCheckoutCompleteOrderTotal(BaseModel):
    gross: "CheckoutCompleteCheckoutCompleteOrderTotalGross"


class CheckoutCompleteCheckoutCompleteOrderTotalGross(BaseModel):
    amount: float
    currency: str


class CheckoutCompleteCheckoutCompleteErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


CheckoutComplete.model_rebuild()
CheckoutCompleteCheckoutComplete.model_rebuild()
CheckoutCompleteCheckoutCompleteOrder.model_rebuild()
CheckoutCompleteCheckoutCompleteOrderTotal.model_rebuild()
