# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Annotated, List, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import CheckoutErrorCode


class CheckoutShippingMethodUpdate(BaseModel):
    checkoutShippingMethodUpdate: Optional[
        "CheckoutShippingMethodUpdateCheckoutShippingMethodUpdate"
    ]


class CheckoutShippingMethodUpdateCheckoutShippingMethodUpdate(BaseModel):
    checkout: Optional[
        "CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckout"
    ]
    errors: List["CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateErrors"]


class CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckout(BaseModel):
    id: str
    deliveryMethod: Optional[
        Annotated[
            Union[
                "CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckoutDeliveryMethodWarehouse",
                "CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckoutDeliveryMethodShippingMethod",
            ],
            Field(discriminator="typename__"),
        ]
    ]
    totalPrice: (
        "CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckoutTotalPrice"
    )


class CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckoutDeliveryMethodWarehouse(
    BaseModel
):
    typename__: Literal["Warehouse"] = Field(alias="__typename")


class CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckoutDeliveryMethodShippingMethod(
    BaseModel
):
    typename__: Literal["ShippingMethod"] = Field(alias="__typename")
    id: str
    name: str


class CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckoutTotalPrice(
    BaseModel
):
    gross: "CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckoutTotalPriceGross"


class CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckoutTotalPriceGross(
    BaseModel
):
    amount: float
    currency: str


class CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


CheckoutShippingMethodUpdate.model_rebuild()
CheckoutShippingMethodUpdateCheckoutShippingMethodUpdate.model_rebuild()
CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckout.model_rebuild()
CheckoutShippingMethodUpdateCheckoutShippingMethodUpdateCheckoutTotalPrice.model_rebuild()
