# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import List, Optional

from .base_model import BaseModel
from .enums import CheckoutErrorCode


class CheckoutBillingAddressUpdate(BaseModel):
    checkoutBillingAddressUpdate: Optional[
        "CheckoutBillingAddressUpdateCheckoutBillingAddressUpdate"
    ]


class CheckoutBillingAddressUpdateCheckoutBillingAddressUpdate(BaseModel):
    checkout: Optional[
        "CheckoutBillingAddressUpdateCheckoutBillingAddressUpdateCheckout"
    ]
    errors: List["CheckoutBillingAddressUpdateCheckoutBillingAddressUpdateErrors"]


class CheckoutBillingAddressUpdateCheckoutBillingAddressUpdateCheckout(BaseModel):
    id: str
    billingAddress: Optional[
        "CheckoutBillingAddressUpdateCheckoutBillingAddressUpdateCheckoutBillingAddress"
    ]


class CheckoutBillingAddressUpdateCheckoutBillingAddressUpdateCheckoutBillingAddress(
    BaseModel
):
    firstName: str
    lastName: str
    streetAddress1: str
    streetAddress2: str
    city: str
    cityArea: str
    postalCode: str
    country: "CheckoutBillingAddressUpdateCheckoutBillingAddressUpdateCheckoutBillingAddressCountry"
    countryArea: str
    phone: Optional[str]


class CheckoutBillingAddressUpdateCheckoutBillingAddressUpdateCheckoutBillingAddressCountry(
    BaseModel
):
    code: str


class CheckoutBillingAddressUpdateCheckoutBillingAddressUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CheckoutErrorCode


CheckoutBillingAddressUpdate.model_rebuild()
CheckoutBillingAddressUpdateCheckoutBillingAddressUpdate.model_rebuild()
CheckoutBillingAddressUpdateCheckoutBillingAddressUpdateCheckout.model_rebuild()
CheckoutBillingAddressUpdateCheckoutBillingAddressUpdateCheckoutBillingAddress.model_rebuild()
