# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Any, Dict, List, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .checkout_billing_address_update import CheckoutBillingAddressUpdate
from .checkout_complete import CheckoutComplete
from .checkout_create import CheckoutCreate
from .checkout_details import CheckoutDetails
from .checkout_email_update import CheckoutEmailUpdate
from .checkout_lines_add import CheckoutLinesAdd
from .checkout_lines_delete import CheckoutLinesDelete
from .checkout_lines_update import CheckoutLinesUpdate
from .checkout_payment_create import CheckoutPaymentCreate
from .checkout_shipping_address_update import CheckoutShippingAddressUpdate
from .checkout_shipping_method_update import CheckoutShippingMethodUpdate
from .count_orders import CountOrders
from .input_types import (
    AddressInput,
    CheckoutCreateInput,
    CheckoutLineInput,
    CheckoutLineUpdateInput,
    CustomerFilterInput,
    OrderFilterInput,
    OrderSortingInput,
    PaymentInput,
    ProductOrder,
    ProductWhereInput,
    PromotionWhereInput,
    StockFilterInput,
    UserSortingInput,
)
from .list_channels import ListChannels
from .list_customers import ListCustomers
from .list_orders import ListOrders
from .list_products import ListProducts
from .list_promotions import ListPromotions
from .list_stocks import ListStocks
from .product_details import ProductDetails
from .track_order import TrackOrder
from .warehouse_details import WarehouseDetails


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def checkout_billing_address_update(
        self, id: str, billingAddress: AddressInput, **kwargs: Any
    ) -> CheckoutBillingAddressUpdate:
        query = gql(
            """
            mutation CheckoutBillingAddressUpdate($id: ID!, $billingAddress: AddressInput!) {
              checkoutBillingAddressUpdate(id: $id, billingAddress: $billingAddress) {
                checkout {
                  id
                  billingAddress {
                    firstName
                    lastName
                    streetAddress1
                    streetAddress2
                    city
                    cityArea
                    postalCode
                    country {
                      code
                    }
                    countryArea
                    phone
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "billingAddress": billingAddress}
        response = await self.execute(
            query=query,
            operation_name="CheckoutBillingAddressUpdate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CheckoutBillingAddressUpdate.model_validate(data)

    async def checkout_complete(self, id: str, **kwargs: Any) -> CheckoutComplete:
        query = gql(
            """
            mutation CheckoutComplete($id: ID!) {
              checkoutComplete(id: $id) {
                order {
                  id
                  number
                  status
                  paymentStatus
                  created
                  total {
                    gross {
                      amount
                      currency
                    }
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query,
            operation_name="CheckoutComplete",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CheckoutComplete.model_validate(data)

    async def checkout_create(
        self, input: CheckoutCreateInput, **kwargs: Any
    ) -> CheckoutCreate:
        query = gql(
            """
            mutation CheckoutCreate($input: CheckoutCreateInput!) {
              checkoutCreate(input: $input) {
                checkout {
                  id
                  token
                  totalPrice {
                    gross {
                      amount
                      currency
                    }
                  }
                  lines {
                    id
                    quantity
                    variant {
                      name
                      product {
                        name
                      }
                    }
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CheckoutCreate", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CheckoutCreate.model_validate(data)

    async def checkout_details(self, id: str, **kwargs: Any) -> CheckoutDetails:
        query = gql(
            """
            query CheckoutDetails($id: ID!) {
              checkout(id: $id) {
                id
                token
                email
                totalPrice {
                  gross {
                    amount
                    currency
                  }
                }
                lines {
                  id
                  quantity
                  variant {
                    id
                    name
                    product {
                      id
                      name
                      thumbnail(size: 64) {
                        url
                      }
                    }
                  }
                }
                shippingAddress {
                  firstName
                  lastName
                  streetAddress1
                  streetAddress2
                  city
                  cityArea
                  postalCode
                  country {
                    code
                  }
                  countryArea
                  phone
                }
                billingAddress {
                  firstName
                  lastName
                  streetAddress1
                  streetAddress2
                  city
                  cityArea
                  postalCode
                  country {
                    code
                  }
                  countryArea
                  phone
                }
                deliveryMethod {
                  __typename
                  ... on ShippingMethod {
                    id
                    name
                  }
                  ... on Warehouse {
                    id
                    name
                  }
                }
                shippingMethods {
                  id
                  name
                  price {
                    amount
                    currency
                  }
                }
                availableShippingMethods {
                  id
                  name
                  price {
                    amount
                    currency
                  }
                }
                availablePaymentGateways {
                  id
                  name
                  config {
                    field
                    value
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="CheckoutDetails", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CheckoutDetails.model_validate(data)

    async def checkout_email_update(
        self, id: str, email: str, **kwargs: Any
    ) -> CheckoutEmailUpdate:
        query = gql(
            """
            mutation CheckoutEmailUpdate($id: ID!, $email: String!) {
              checkoutEmailUpdate(id: $id, email: $email) {
                checkout {
                  id
                  email
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "email": email}
        response = await self.execute(
            query=query,
            operation_name="CheckoutEmailUpdate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CheckoutEmailUpdate.model_validate(data)

    async def checkout_lines_add(
        self,
        lines: List[CheckoutLineInput],
        id: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> CheckoutLinesAdd:
        query = gql(
            """
            mutation CheckoutLinesAdd($id: ID, $lines: [CheckoutLineInput!]!) {
              checkoutLinesAdd(id: $id, lines: $lines) {
                checkout {
                  id
                  lines {
                    id
                    quantity
                    variant {
                      name
                    }
                  }
                  totalPrice {
                    gross {
                      amount
                      currency
                    }
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "lines": lines}
        response = await self.execute(
            query=query,
            operation_name="CheckoutLinesAdd",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CheckoutLinesAdd.model_validate(data)

    async def checkout_lines_delete(
        self,
        linesIds: List[str],
        id: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> CheckoutLinesDelete:
        query = gql(
            """
            mutation CheckoutLinesDelete($id: ID, $linesIds: [ID!]!) {
              checkoutLinesDelete(id: $id, linesIds: $linesIds) {
                checkout {
                  id
                  lines {
                    id
                    quantity
                  }
                  totalPrice {
                    gross {
                      amount
                      currency
                    }
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "linesIds": linesIds}
        response = await self.execute(
            query=query,
            operation_name="CheckoutLinesDelete",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CheckoutLinesDelete.model_validate(data)

    async def checkout_lines_update(
        self,
        lines: List[CheckoutLineUpdateInput],
        id: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> CheckoutLinesUpdate:
        query = gql(
            """
            mutation CheckoutLinesUpdate($id: ID, $lines: [CheckoutLineUpdateInput!]!) {
              checkoutLinesUpdate(id: $id, lines: $lines) {
                checkout {
                  id
                  lines {
                    id
                    quantity
                    variant {
                      name
                    }
                  }
                  totalPrice {
                    gross {
                      amount
                      currency
                    }
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "lines": lines}
        response = await self.execute(
            query=query,
            operation_name="CheckoutLinesUpdate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CheckoutLinesUpdate.model_validate(data)

    async def checkout_payment_create(
        self, id: str, input: PaymentInput, **kwargs: Any
    ) -> CheckoutPaymentCreate:
        query = gql(
            """
            mutation CheckoutPaymentCreate($id: ID!, $input: PaymentInput!) {
              checkoutPaymentCreate(id: $id, input: $input) {
                payment {
                  id
                  gateway
                  isActive
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query,
            operation_name="CheckoutPaymentCreate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CheckoutPaymentCreate.model_validate(data)

    async def checkout_shipping_address_update(
        self, id: str, shippingAddress: AddressInput, **kwargs: Any
    ) -> CheckoutShippingAddressUpdate:
        query = gql(
            """
            mutation CheckoutShippingAddressUpdate($id: ID!, $shippingAddress: AddressInput!) {
              checkoutShippingAddressUpdate(id: $id, shippingAddress: $shippingAddress) {
                checkout {
                  id
                  shippingAddress {
                    firstName
                    lastName
                    streetAddress1
                    streetAddress2
                    city
                    cityArea
                    postalCode
                    country {
                      code
                    }
                    countryArea
                    phone
                  }
                  availableShippingMethods {
                    id
                    name
                    price {
                      amount
                      currency
                    }
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "shippingAddress": shippingAddress}
        response = await self.execute(
            query=query,
            operation_name="CheckoutShippingAddressUpdate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CheckoutShippingAddressUpdate.model_validate(data)

    async def checkout_shipping_method_update(
        self, id: str, shippingMethodId: str, **kwargs: Any
    ) -> CheckoutShippingMethodUpdate:
        query = gql(
            """
            mutation CheckoutShippingMethodUpdate($id: ID!, $shippingMethodId: ID!) {
              checkoutShippingMethodUpdate(id: $id, shippingMethodId: $shippingMethodId) {
                checkout {
                  id
                  deliveryMethod {
                    __typename
                    ... on ShippingMethod {
                      id
                      name
                    }
                  }
                  totalPrice {
                    gross {
                      amount
                      currency
                    }
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "shippingMethodId": shippingMethodId}
        response = await self.execute(
            query=query,
            operation_name="CheckoutShippingMethodUpdate",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return CheckoutShippingMethodUpdate.model_validate(data)

    async def count_orders(
        self,
        filter: Union[Optional[OrderFilterInput], UnsetType] = UNSET,
        **kwargs: Any
    ) -> CountOrders:
        query = gql(
            """
            query CountOrders($filter: OrderFilterInput) {
              orders(filter: $filter) {
                totalCount
              }
            }
            """
        )
        variables: Dict[str, object] = {"filter": filter}
        response = await self.execute(
            query=query, operation_name="CountOrders", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CountOrders.model_validate(data)

    async def list_channels(self, **kwargs: Any) -> ListChannels:
        query = gql(
            """
            query ListChannels {
              channels {
                id
                slug
                name
                isActive
                currencyCode
                defaultCountry {
                  code
                }
                warehouses {
                  id
                  name
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="ListChannels", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListChannels.model_validate(data)

    async def list_customers(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        sortBy: Union[Optional[UserSortingInput], UnsetType] = UNSET,
        filter: Union[Optional[CustomerFilterInput], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ListCustomers:
        query = gql(
            """
            query ListCustomers($first: Int, $after: String, $sortBy: UserSortingInput, $filter: CustomerFilterInput) {
              customers(first: $first, after: $after, sortBy: $sortBy, filter: $filter) {
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  startCursor
                  endCursor
                }
                totalCount
                edges {
                  node {
                    id
                    isActive
                    languageCode
                    lastLogin
                    dateJoined
                    defaultShippingAddress {
                      country {
                        code
                      }
                    }
                    defaultBillingAddress {
                      country {
                        code
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "first": first,
            "after": after,
            "sortBy": sortBy,
            "filter": filter,
        }
        response = await self.execute(
            query=query, operation_name="ListCustomers", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListCustomers.model_validate(data)

    async def list_orders(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        sortBy: Union[Optional[OrderSortingInput], UnsetType] = UNSET,
        filter: Union[Optional[OrderFilterInput], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ListOrders:
        query = gql(
            """
            query ListOrders($first: Int, $after: String, $sortBy: OrderSortingInput, $filter: OrderFilterInput) {
              orders(first: $first, after: $after, sortBy: $sortBy, filter: $filter) {
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  startCursor
                  endCursor
                }
                totalCount
                edges {
                  node {
                    id
                    number
                    status
                    created
                    updatedAt
                    paymentStatus
                    total {
                      gross {
                        amount
                        currency
                      }
                    }
                    lines {
                      quantity
                      productSku
                      variant {
                        name
                        product {
                          id
                          name
                        }
                      }
                      unitPrice {
                        gross {
                          currency
                          amount
                        }
                      }
                    }
                    shippingAddress {
                      country {
                        code
                      }
                    }
                    billingAddress {
                      country {
                        code
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "first": first,
            "after": after,
            "sortBy": sortBy,
            "filter": filter,
        }
        response = await self.execute(
            query=query, operation_name="ListOrders", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListOrders.model_validate(data)

    async def list_products(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        channel: Union[Optional[str], UnsetType] = UNSET,
        where: Union[Optional[ProductWhereInput], UnsetType] = UNSET,
        sortBy: Union[Optional[ProductOrder], UnsetType] = UNSET,
        search: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ListProducts:
        query = gql(
            """
            query ListProducts($first: Int, $after: String, $channel: String, $where: ProductWhereInput, $sortBy: ProductOrder, $search: String) {
              products(
                first: $first
                after: $after
                channel: $channel
                where: $where
                sortBy: $sortBy
                search: $search
              ) {
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  startCursor
                  endCursor
                }
                totalCount
                edges {
                  node {
                    id
                    name
                    slug
                    externalReference
                    productType {
                      id
                      name
                    }
                    category {
                      id
                      name
                    }
                    defaultVariant {
                      id
                    }
                    productVariants(first: 20) {
                      edges {
                        node {
                          id
                          name
                          sku
                        }
                      }
                    }
                    created
                    updatedAt
                    thumbnail(size: 64) {
                      url
                    }
                    pricing {
                      priceRange {
                        start {
                          gross {
                            currency
                            amount
                          }
                        }
                        stop {
                          gross {
                            currency
                            amount
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "first": first,
            "after": after,
            "channel": channel,
            "where": where,
            "sortBy": sortBy,
            "search": search,
        }
        response = await self.execute(
            query=query, operation_name="ListProducts", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListProducts.model_validate(data)

    async def list_promotions(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        where: Union[Optional[PromotionWhereInput], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ListPromotions:
        query = gql(
            """
            query ListPromotions($first: Int, $after: String, $where: PromotionWhereInput) {
              promotions(first: $first, after: $after, where: $where) {
                edges {
                  node {
                    id
                    name
                    description
                    startDate
                    endDate
                    rules {
                      id
                      name
                      description
                      channels {
                        slug
                      }
                      rewardValueType
                      rewardValue
                    }
                  }
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"first": first, "after": after, "where": where}
        response = await self.execute(
            query=query, operation_name="ListPromotions", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListPromotions.model_validate(data)

    async def list_stocks(
        self,
        first: Union[Optional[int], UnsetType] = UNSET,
        after: Union[Optional[str], UnsetType] = UNSET,
        filter: Union[Optional[StockFilterInput], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ListStocks:
        query = gql(
            """
            query ListStocks($first: Int, $after: String, $filter: StockFilterInput) {
              stocks(first: $first, after: $after, filter: $filter) {
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  startCursor
                  endCursor
                }
                totalCount
                edges {
                  node {
                    id
                    quantity
                    quantityAllocated
                    warehouse {
                      id
                    }
                    productVariant {
                      id
                      name
                      product {
                        id
                        name
                      }
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "first": first,
            "after": after,
            "filter": filter,
        }
        response = await self.execute(
            query=query, operation_name="ListStocks", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListStocks.model_validate(data)

    async def product_details(
        self,
        id: Union[Optional[str], UnsetType] = UNSET,
        slug: Union[Optional[str], UnsetType] = UNSET,
        channel: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> ProductDetails:
        query = gql(
            """
            query ProductDetails($id: ID, $slug: String, $channel: String) {
              product(id: $id, slug: $slug, channel: $channel) {
                id
                name
                slug
                description
                category {
                  name
                }
                media {
                  url
                  alt
                }
                variants {
                  id
                  name
                  sku
                  pricing {
                    price {
                      gross {
                        amount
                        currency
                      }
                    }
                  }
                  attributes {
                    attribute {
                      name
                    }
                    values {
                      name
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id, "slug": slug, "channel": channel}
        response = await self.execute(
            query=query, operation_name="ProductDetails", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ProductDetails.model_validate(data)

    async def track_order(
        self,
        id: Union[Optional[str], UnsetType] = UNSET,
        externalReference: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> TrackOrder:
        query = gql(
            """
            query TrackOrder($id: ID, $externalReference: String) {
              order(id: $id, externalReference: $externalReference) {
                id
                number
                status
                created
                fulfillments {
                  id
                  fulfillmentOrder
                  status
                  trackingNumber
                  created
                }
                shippingAddress {
                  streetAddress1
                  city
                  postalCode
                  country {
                    country
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "id": id,
            "externalReference": externalReference,
        }
        response = await self.execute(
            query=query, operation_name="TrackOrder", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return TrackOrder.model_validate(data)

    async def warehouse_details(
        self, id: Union[Optional[str], UnsetType] = UNSET, **kwargs: Any
    ) -> WarehouseDetails:
        query = gql(
            """
            query WarehouseDetails($id: ID) {
              warehouse(id: $id) {
                id
                name
                slug
                address {
                  city
                  postalCode
                  country {
                    code
                  }
                }
                clickAndCollectOption
                shippingZones(first: 100) {
                  edges {
                    node {
                      id
                      name
                      description
                      channels {
                        id
                        slug
                        name
                      }
                      countries {
                        code
                      }
                    }
                  }
                }
                metadata {
                  key
                  value
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"id": id}
        response = await self.execute(
            query=query,
            operation_name="WarehouseDetails",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return WarehouseDetails.model_validate(data)
