# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import RewardValueTypeEnum


class ListPromotions(BaseModel):
    promotions: Optional["ListPromotionsPromotions"]


class ListPromotionsPromotions(BaseModel):
    edges: List["ListPromotionsPromotionsEdges"]
    pageInfo: "ListPromotionsPromotionsPageInfo"


class ListPromotionsPromotionsEdges(BaseModel):
    node: "ListPromotionsPromotionsEdgesNode"


class ListPromotionsPromotionsEdgesNode(BaseModel):
    id: str
    name: str
    description: Optional[Any]
    startDate: Any
    endDate: Optional[Any]
    rules: Optional[List["ListPromotionsPromotionsEdgesNodeRules"]]


class ListPromotionsPromotionsEdgesNodeRules(BaseModel):
    id: str
    name: Optional[str]
    description: Optional[Any]
    channels: Optional[List["ListPromotionsPromotionsEdgesNodeRulesChannels"]]
    rewardValueType: Optional[RewardValueTypeEnum]
    rewardValue: Optional[Any]


class ListPromotionsPromotionsEdgesNodeRulesChannels(BaseModel):
    slug: str


class ListPromotionsPromotionsPageInfo(BaseModel):
    hasNextPage: bool
    endCursor: Optional[str]


ListPromotions.model_rebuild()
ListPromotionsPromotions.model_rebuild()
ListPromotionsPromotionsEdges.model_rebuild()
ListPromotionsPromotionsEdgesNode.model_rebuild()
ListPromotionsPromotionsEdgesNodeRules.model_rebuild()
