# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Any, Optional

from .base_model import BaseModel
from .enums import LanguageCodeEnum


class Me(BaseModel):
    me: Optional["MeMe"]


class MeMe(BaseModel):
    id: str
    email: str
    firstName: str
    lastName: str
    isActive: bool
    isStaff: bool
    languageCode: LanguageCodeEnum
    dateJoined: Any
    lastLogin: Optional[Any]
    defaultShippingAddress: Optional["MeMeDefaultShippingAddress"]


class MeMeDefaultShippingAddress(BaseModel):
    country: "MeMeDefaultShippingAddressCountry"


class MeMeDefaultShippingAddressCountry(BaseModel):
    code: str


Me.model_rebuild()
MeMe.model_rebuild()
MeMeDefaultShippingAddress.model_rebuild()
