# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Any, List, Optional

from .base_model import BaseModel


class ProductDetails(BaseModel):
    product: Optional["ProductDetailsProduct"]


class ProductDetailsProduct(BaseModel):
    id: str
    name: str
    slug: str
    description: Optional[Any]
    category: Optional["ProductDetailsProductCategory"]
    thumbnail: Optional["ProductDetailsProductThumbnail"]
    media: Optional[List["ProductDetailsProductMedia"]]
    variants: Optional[List["ProductDetailsProductVariants"]]


class ProductDetailsProductCategory(BaseModel):
    name: str


class ProductDetailsProductThumbnail(BaseModel):
    url: str


class ProductDetailsProductMedia(BaseModel):
    url: str
    alt: str


class ProductDetailsProductVariants(BaseModel):
    id: str
    name: str
    sku: Optional[str]
    pricing: Optional["ProductDetailsProductVariantsPricing"]
    attributes: List["ProductDetailsProductVariantsAttributes"]


class ProductDetailsProductVariantsPricing(BaseModel):
    price: Optional["ProductDetailsProductVariantsPricingPrice"]


class ProductDetailsProductVariantsPricingPrice(BaseModel):
    gross: "ProductDetailsProductVariantsPricingPriceGross"


class ProductDetailsProductVariantsPricingPriceGross(BaseModel):
    amount: float
    currency: str


class ProductDetailsProductVariantsAttributes(BaseModel):
    attribute: "ProductDetailsProductVariantsAttributesAttribute"
    values: List["ProductDetailsProductVariantsAttributesValues"]


class ProductDetailsProductVariantsAttributesAttribute(BaseModel):
    name: Optional[str]


class ProductDetailsProductVariantsAttributesValues(BaseModel):
    name: Optional[str]


ProductDetails.model_rebuild()
ProductDetailsProduct.model_rebuild()
ProductDetailsProductVariants.model_rebuild()
ProductDetailsProductVariantsPricing.model_rebuild()
ProductDetailsProductVariantsPricingPrice.model_rebuild()
ProductDetailsProductVariantsAttributes.model_rebuild()
