# Generated by ariadne-codegen
# Source: src/saleor_mcp/graphql

from typing import Any, List, Optional

from .base_model import BaseModel
from .enums import FulfillmentStatus, OrderStatus


class TrackOrder(BaseModel):
    order: Optional["TrackOrderOrder"]


class TrackOrderOrder(BaseModel):
    id: str
    number: str
    status: OrderStatus
    created: Any
    fulfillments: List["TrackOrderOrderFulfillments"]
    shippingAddress: Optional["TrackOrderOrderShippingAddress"]


class TrackOrderOrderFulfillments(BaseModel):
    id: str
    fulfillmentOrder: int
    status: FulfillmentStatus
    trackingNumber: str
    created: Any


class TrackOrderOrderShippingAddress(BaseModel):
    streetAddress1: str
    city: str
    postalCode: str
    country: "TrackOrderOrderShippingAddressCountry"


class TrackOrderOrderShippingAddressCountry(BaseModel):
    country: str


TrackOrder.model_rebuild()
TrackOrderOrder.model_rebuild()
TrackOrderOrderShippingAddress.model_rebuild()
